from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List, Tuple


# This catalog is business-type metadata, not scenario output data.
# Municipalities remain data-driven from the census feature dataset.
# These values describe how each supported business type behaves so the
# feature builder, OSM lookup, demand, lease, and competition services can use
# one shared source instead of scattered if/else logic.

BASE_PROFILE: Dict[str, Any] = {
    "category": "General Retail / Service",
    "subcategory": "General Business",
    "avg_ticket": 18.0,
    "gross_margin_pct": 0.48,
    "space_sqft": 1500,
    "monthly_staff_cost": 12000,
    "monthly_utilities": 1200,
    "base_capture_rate": 0.0024,
    "student_weight": 0.7,
    "young_adult_weight": 0.9,
    "family_weight": 0.9,
    "senior_weight": 0.6,
    "diversity_weight": 0.7,
    "immigrant_weight": 0.7,
    "income_sensitivity": 0.85,
    "density_sensitivity": 0.85,
    "competition_sensitivity": 1.0,
    "lease_sensitivity": 1.0,
    "labour_fit_column": "working_age_25_64_pct",
    "osm_tags": [("shop", "yes")],
}


def _profile(**overrides: Any) -> Dict[str, Any]:
    row = deepcopy(BASE_PROFILE)
    row.update(overrides)
    return row


BUSINESS_SUBCATEGORY_CATALOG: List[Dict[str, Any]] = [
    _profile(
        category="Grocery / Food Retail",
        subcategory="Indian Grocery Store",
        avg_ticket=34.0,
        gross_margin_pct=0.34,
        space_sqft=2200,
        monthly_staff_cost=15500,
        monthly_utilities=1850,
        base_capture_rate=0.0029,
        family_weight=1.25,
        diversity_weight=1.35,
        immigrant_weight=1.45,
        competition_sensitivity=1.10,
        lease_sensitivity=1.05,
        osm_tags=[("shop", "supermarket"), ("shop", "convenience"), ("shop", "greengrocer")],
    ),
    _profile(
        category="Grocery / Food Retail",
        subcategory="General Grocery Store",
        avg_ticket=31.0,
        gross_margin_pct=0.31,
        space_sqft=2600,
        monthly_staff_cost=17500,
        monthly_utilities=2100,
        base_capture_rate=0.0031,
        family_weight=1.20,
        senior_weight=0.90,
        competition_sensitivity=1.18,
        lease_sensitivity=1.10,
        osm_tags=[("shop", "supermarket"), ("shop", "convenience"), ("shop", "greengrocer")],
    ),
    _profile(
        category="Grocery / Food Retail",
        subcategory="Chinese Grocery Store",
        avg_ticket=32.0,
        gross_margin_pct=0.33,
        space_sqft=2100,
        monthly_staff_cost=15000,
        monthly_utilities=1800,
        base_capture_rate=0.0027,
        family_weight=1.10,
        diversity_weight=1.40,
        immigrant_weight=1.45,
        competition_sensitivity=1.05,
        osm_tags=[("shop", "supermarket"), ("shop", "greengrocer"), ("shop", "convenience")],
    ),
    _profile(
        category="Grocery / Food Retail",
        subcategory="Halal Grocery Store",
        avg_ticket=33.0,
        gross_margin_pct=0.34,
        space_sqft=2000,
        monthly_staff_cost=14500,
        monthly_utilities=1750,
        base_capture_rate=0.0026,
        family_weight=1.20,
        diversity_weight=1.35,
        immigrant_weight=1.40,
        osm_tags=[("shop", "supermarket"), ("shop", "butcher"), ("shop", "convenience")],
    ),
    _profile(
        category="Food Service",
        subcategory="Coffee Shop / Cafe",
        avg_ticket=9.50,
        gross_margin_pct=0.62,
        space_sqft=1200,
        monthly_staff_cost=16500,
        monthly_utilities=1600,
        base_capture_rate=0.0038,
        student_weight=1.25,
        young_adult_weight=1.25,
        density_sensitivity=1.18,
        competition_sensitivity=1.22,
        lease_sensitivity=1.05,
        osm_tags=[("amenity", "cafe")],
    ),
    _profile(
        category="Food Service",
        subcategory="Bubble Tea Shop",
        avg_ticket=8.75,
        gross_margin_pct=0.64,
        space_sqft=950,
        monthly_staff_cost=14500,
        monthly_utilities=1400,
        base_capture_rate=0.0032,
        student_weight=1.45,
        young_adult_weight=1.35,
        density_sensitivity=1.22,
        competition_sensitivity=1.18,
        osm_tags=[("amenity", "cafe"), ("shop", "tea")],
    ),
    _profile(
        category="Food Service",
        subcategory="Fast Food Restaurant",
        avg_ticket=13.50,
        gross_margin_pct=0.56,
        space_sqft=1800,
        monthly_staff_cost=24000,
        monthly_utilities=2600,
        base_capture_rate=0.0041,
        student_weight=1.05,
        young_adult_weight=1.10,
        family_weight=1.05,
        density_sensitivity=1.15,
        competition_sensitivity=1.28,
        lease_sensitivity=1.15,
        osm_tags=[("amenity", "fast_food")],
    ),
    _profile(
        category="Food Service",
        subcategory="Casual Restaurant",
        avg_ticket=28.0,
        gross_margin_pct=0.55,
        space_sqft=2500,
        monthly_staff_cost=32000,
        monthly_utilities=3600,
        base_capture_rate=0.0024,
        family_weight=1.05,
        income_sensitivity=1.10,
        density_sensitivity=1.05,
        competition_sensitivity=1.25,
        lease_sensitivity=1.20,
        osm_tags=[("amenity", "restaurant")],
    ),
    _profile(
        category="Food Service",
        subcategory="Pizza Shop",
        avg_ticket=22.0,
        gross_margin_pct=0.58,
        space_sqft=1400,
        monthly_staff_cost=19000,
        monthly_utilities=2200,
        base_capture_rate=0.0033,
        family_weight=1.15,
        young_adult_weight=1.00,
        competition_sensitivity=1.25,
        osm_tags=[("amenity", "restaurant"), ("amenity", "fast_food")],
    ),
    _profile(
        category="Food Service",
        subcategory="Bakery",
        avg_ticket=14.0,
        gross_margin_pct=0.60,
        space_sqft=1300,
        monthly_staff_cost=17000,
        monthly_utilities=2100,
        base_capture_rate=0.0029,
        family_weight=1.05,
        income_sensitivity=1.05,
        density_sensitivity=1.00,
        competition_sensitivity=1.12,
        osm_tags=[("shop", "bakery")],
    ),
    _profile(
        category="Health / Wellness",
        subcategory="Fitness Center",
        avg_ticket=58.0,
        gross_margin_pct=0.72,
        space_sqft=5200,
        monthly_staff_cost=25000,
        monthly_utilities=4600,
        base_capture_rate=0.0013,
        young_adult_weight=1.35,
        working_age_weight=1.00,
        income_sensitivity=1.10,
        density_sensitivity=0.95,
        competition_sensitivity=1.10,
        lease_sensitivity=1.35,
        osm_tags=[("leisure", "fitness_centre"), ("amenity", "gym")],
    ),
    _profile(
        category="Health / Wellness",
        subcategory="Yoga Studio",
        avg_ticket=34.0,
        gross_margin_pct=0.70,
        space_sqft=1800,
        monthly_staff_cost=14000,
        monthly_utilities=1500,
        base_capture_rate=0.0015,
        young_adult_weight=1.25,
        income_sensitivity=1.18,
        density_sensitivity=1.05,
        competition_sensitivity=1.05,
        osm_tags=[("leisure", "fitness_centre"), ("sport", "yoga")],
    ),
    _profile(
        category="Health / Wellness",
        subcategory="Physiotherapy Clinic",
        avg_ticket=92.0,
        gross_margin_pct=0.68,
        space_sqft=1800,
        monthly_staff_cost=28000,
        monthly_utilities=1500,
        base_capture_rate=0.0009,
        senior_weight=1.10,
        working_age_weight=1.15,
        income_sensitivity=1.12,
        density_sensitivity=0.90,
        competition_sensitivity=0.95,
        osm_tags=[("healthcare", "physiotherapist"), ("amenity", "clinic")],
    ),
    _profile(
        category="Health / Wellness",
        subcategory="Pharmacy",
        avg_ticket=42.0,
        gross_margin_pct=0.42,
        space_sqft=2400,
        monthly_staff_cost=30000,
        monthly_utilities=1900,
        base_capture_rate=0.0020,
        family_weight=1.05,
        senior_weight=1.35,
        income_sensitivity=0.90,
        competition_sensitivity=1.12,
        lease_sensitivity=1.10,
        osm_tags=[("amenity", "pharmacy"), ("shop", "chemist")],
    ),
    _profile(
        category="Health / Wellness",
        subcategory="Dental Clinic",
        avg_ticket=160.0,
        gross_margin_pct=0.63,
        space_sqft=2200,
        monthly_staff_cost=36000,
        monthly_utilities=1700,
        base_capture_rate=0.00055,
        family_weight=1.10,
        income_sensitivity=1.20,
        competition_sensitivity=0.95,
        lease_sensitivity=1.15,
        osm_tags=[("amenity", "dentist")],
    ),
    _profile(
        category="Education / Child Services",
        subcategory="Tutoring Center",
        avg_ticket=48.0,
        gross_margin_pct=0.74,
        space_sqft=1400,
        monthly_staff_cost=18000,
        monthly_utilities=1100,
        base_capture_rate=0.0010,
        family_weight=1.45,
        student_weight=1.20,
        income_sensitivity=1.15,
        competition_sensitivity=0.90,
        osm_tags=[("amenity", "school"), ("office", "educational_institution")],
    ),
    _profile(
        category="Education / Child Services",
        subcategory="Daycare Center",
        avg_ticket=120.0,
        gross_margin_pct=0.58,
        space_sqft=3200,
        monthly_staff_cost=42000,
        monthly_utilities=2300,
        base_capture_rate=0.00065,
        family_weight=1.70,
        income_sensitivity=1.05,
        competition_sensitivity=0.85,
        lease_sensitivity=1.25,
        osm_tags=[("amenity", "kindergarten"), ("amenity", "childcare")],
    ),
    _profile(
        category="Personal Services",
        subcategory="Hair Salon",
        avg_ticket=54.0,
        gross_margin_pct=0.66,
        space_sqft=1200,
        monthly_staff_cost=17000,
        monthly_utilities=1200,
        base_capture_rate=0.0014,
        young_adult_weight=1.10,
        family_weight=0.90,
        income_sensitivity=1.05,
        competition_sensitivity=1.20,
        osm_tags=[("shop", "hairdresser"), ("shop", "beauty")],
    ),
    _profile(
        category="Personal Services",
        subcategory="Nail Salon",
        avg_ticket=46.0,
        gross_margin_pct=0.67,
        space_sqft=1000,
        monthly_staff_cost=15500,
        monthly_utilities=1100,
        base_capture_rate=0.0012,
        young_adult_weight=1.20,
        income_sensitivity=1.12,
        competition_sensitivity=1.15,
        osm_tags=[("shop", "beauty"), ("shop", "cosmetics")],
    ),
    _profile(
        category="Personal Services",
        subcategory="Barbershop",
        avg_ticket=36.0,
        gross_margin_pct=0.66,
        space_sqft=900,
        monthly_staff_cost=13500,
        monthly_utilities=950,
        base_capture_rate=0.0013,
        young_adult_weight=1.10,
        density_sensitivity=1.05,
        competition_sensitivity=1.15,
        osm_tags=[("shop", "hairdresser")],
    ),
    _profile(
        category="Personal Services",
        subcategory="Laundromat",
        avg_ticket=16.0,
        gross_margin_pct=0.70,
        space_sqft=1800,
        monthly_staff_cost=8500,
        monthly_utilities=3600,
        base_capture_rate=0.0019,
        renter_weight=1.25,
        income_sensitivity=0.70,
        density_sensitivity=1.18,
        competition_sensitivity=0.95,
        lease_sensitivity=1.05,
        osm_tags=[("shop", "laundry"), ("amenity", "laundry")],
    ),
    _profile(
        category="Retail",
        subcategory="Clothing Boutique",
        avg_ticket=68.0,
        gross_margin_pct=0.57,
        space_sqft=1400,
        monthly_staff_cost=14500,
        monthly_utilities=1100,
        base_capture_rate=0.0011,
        young_adult_weight=1.10,
        income_sensitivity=1.30,
        density_sensitivity=1.08,
        competition_sensitivity=1.05,
        osm_tags=[("shop", "clothes")],
    ),
    _profile(
        category="Retail",
        subcategory="Pet Supply Store",
        avg_ticket=52.0,
        gross_margin_pct=0.45,
        space_sqft=1800,
        monthly_staff_cost=13000,
        monthly_utilities=1200,
        base_capture_rate=0.0010,
        family_weight=1.05,
        income_sensitivity=1.05,
        competition_sensitivity=0.90,
        osm_tags=[("shop", "pet")],
    ),
    _profile(
        category="Retail / Repair",
        subcategory="Electronics Repair Shop",
        avg_ticket=82.0,
        gross_margin_pct=0.62,
        space_sqft=900,
        monthly_staff_cost=13500,
        monthly_utilities=900,
        base_capture_rate=0.0008,
        student_weight=1.05,
        young_adult_weight=1.20,
        income_sensitivity=0.95,
        density_sensitivity=1.05,
        competition_sensitivity=0.85,
        osm_tags=[("shop", "electronics"), ("craft", "electronics_repair")],
    ),
    _profile(
        category="Retail",
        subcategory="Florist",
        avg_ticket=44.0,
        gross_margin_pct=0.55,
        space_sqft=900,
        monthly_staff_cost=11500,
        monthly_utilities=850,
        base_capture_rate=0.0008,
        income_sensitivity=1.10,
        density_sensitivity=0.95,
        competition_sensitivity=0.85,
        osm_tags=[("shop", "florist")],
    ),
    _profile(
        category="Grocery / Food Retail",
        subcategory="Convenience Store",
        avg_ticket=15.0,
        gross_margin_pct=0.38,
        space_sqft=1600,
        monthly_staff_cost=18000,
        monthly_utilities=1700,
        base_capture_rate=0.0030,
        density_sensitivity=1.20,
        competition_sensitivity=1.18,
        lease_sensitivity=1.05,
        osm_tags=[("shop", "convenience")],
    ),
]


_BY_SUBCATEGORY = {
    row["subcategory"].lower().strip(): row for row in BUSINESS_SUBCATEGORY_CATALOG
}


def list_business_subcategory_profiles() -> List[Dict[str, Any]]:
    return [deepcopy(row) for row in BUSINESS_SUBCATEGORY_CATALOG]


def list_business_subcategory_options() -> List[Dict[str, str]]:
    rows = sorted(BUSINESS_SUBCATEGORY_CATALOG, key=lambda row: (row["category"], row["subcategory"]))
    return [
        {
            "business_category": str(row["category"]),
            "business_subcategory": str(row["subcategory"]),
            "label": f"{row['subcategory']} — {row['category']}",
        }
        for row in rows
    ]


def get_business_profile_dict(business_subcategory: str) -> Dict[str, Any]:
    key = business_subcategory.lower().strip()
    if key not in _BY_SUBCATEGORY:
        available = ", ".join(sorted(row["subcategory"] for row in BUSINESS_SUBCATEGORY_CATALOG)[:12])
        raise ValueError(
            f"Business subcategory not found: {business_subcategory}. "
            f"Example available subcategories: {available}"
        )
    return deepcopy(_BY_SUBCATEGORY[key])


def get_osm_tags_for_subcategory(business_subcategory: str) -> List[Tuple[str, str]]:
    try:
        profile = get_business_profile_dict(business_subcategory)
    except ValueError:
        return [("shop", "yes"), ("amenity", "restaurant")]
    return list(profile.get("osm_tags") or [("shop", "yes")])
